"""Detect machine-generated inbound mail (newsletters, bulk, spam-flagged).

Znuny's PostMaster already folds the classic loop markers (``Precedence``,
``Auto-Submitted``, ``Mailing-List``, ``X-Loop``, ``X-No-Loop``) into a single
``X-OTRS-Loop`` header, and that header is what suppresses the *autoresponse*
— see :func:`tiqora.channels.email.pipeline._build_get_param`. The AI
auto-reply never consulted it, so a newsletter could still be answered by the
agent runtime.

:func:`is_auto_generated` is a deliberate **superset** of ``X-OTRS-Loop``
rather than an extension of it: widening the loop folding itself would change
autoresponse behaviour and drift from the Znuny port this pipeline
reproduces. The extra markers (``List-Unsubscribe``/``List-Id`` — set by every
serious newsletter but by no autoresponder, and ``X-Spam-Flag``/
``X-Spam-Status`` from an upstream filter) only gate the AI auto-reply, which
has no Znuny counterpart to stay compatible with.

The flag rides along on ``ArticleIn.auto_generated`` into the
``ArticleCreate`` outbox payload, where
:mod:`tiqora.ai.auto_worker` reads it. Detection therefore has to happen at
ingest: Tiqora does not store raw MIME (``article_data_mime_plain`` is empty),
so these headers are unavailable to anything downstream.
"""

from __future__ import annotations

from collections.abc import Mapping

# Header names that mark a message as machine-generated by their mere
# presence — a value check would be wrong here (``List-Unsubscribe`` carries a
# URL, ``List-Id`` a list name; neither has a "no" form).
_PRESENCE_MARKERS = ("list-unsubscribe", "list-id", "list-post")

# Headers whose *value* decides. An upstream spam filter writes
# ``X-Spam-Flag: YES`` and ``X-Spam-Status: Yes, score=...`` — both start with
# "yes"; a clean message gets "NO"/"No, score=..." and must not match.
_SPAM_MARKERS = ("x-spam-flag", "x-spam-status")


def _lookup(headers: Mapping[str, str], name: str) -> str | None:
    """Case-insensitive header read.

    ``get_param`` stores every header twice (canonical case and lowercase),
    but postmaster filters and ``X-OTRS-*`` injection may add only one
    spelling — so never rely on a single casing.
    """
    for key in (name, name.title(), name.upper()):
        value = headers.get(key)
        if value is not None:
            return value
    lowered = name.lower()
    for key, value in headers.items():
        if key.lower() == lowered:
            return value
    return None


def is_auto_generated(headers: Mapping[str, str]) -> bool:
    """``True`` when *headers* mark the message as machine-generated.

    *headers* is the pipeline's ``get_param`` map, read **after**
    ``apply_filters`` so an admin's postmaster filter setting ``X-OTRS-Loop``
    is honoured too.
    """
    loop = (_lookup(headers, "X-OTRS-Loop") or "").strip().lower()
    if loop in ("yes", "true", "1"):
        return True

    for marker in _PRESENCE_MARKERS:
        if (_lookup(headers, marker) or "").strip():
            return True

    for marker in _SPAM_MARKERS:
        if (_lookup(headers, marker) or "").strip().lower().startswith("yes"):
            return True

    return False


__all__ = ["is_auto_generated"]
