"""Hand-written SQLAlchemy models for Znuny 6.5 tables (Phase 0+).

These map the shared Znuny schema for parallel operation. They use a separate
MetaData instance and must never be managed by Alembic.
"""

from tiqora.db.legacy.article import (  # noqa: F401
    Article,
    ArticleDataMime,
    ArticleDataMimeAttachment,
    ArticleDataMimePlain,
    ArticleFlag,
    ArticleSearchIndex,
    ArticleSenderType,
    CommunicationChannel,
)
from tiqora.db.legacy.base import LegacyBase, legacy_metadata
from tiqora.db.legacy.config import (  # noqa: F401
    Acl,
    GenericAgentJobs,
    GiWebserviceConfig,
    MailQueue,
    PostmasterFilter,
    Sessions,
    SysconfigDefault,
    SysconfigModified,
    Valid,
)
from tiqora.db.legacy.customer import (  # noqa: F401
    CustomerCompany,
    CustomerPreferences,
    CustomerUser,
    CustomerUserCustomer,
)
from tiqora.db.legacy.dynamic_field import (  # noqa: F401
    DynamicField,
    DynamicFieldObjIdName,
    DynamicFieldValue,
)
from tiqora.db.legacy.mail_account import MailAccount  # noqa: F401
from tiqora.db.legacy.misc import (  # noqa: F401
    FormDraft,
    LinkObject,
    LinkRelation,
    LinkType,
    Mention,
    TimeAccounting,
)
from tiqora.db.legacy.queue import (  # noqa: F401
    AutoResponse,
    AutoResponseType,
    FollowUpPossible,
    Queue,
    QueueAutoResponse,
    QueueStandardTemplate,
    Salutation,
    Service,
    ServiceCustomerUser,
    ServiceSla,
    Signature,
    Sla,
    StandardAttachment,
    StandardTemplate,
    StandardTemplateAttachment,
    SystemAddress,
)
from tiqora.db.legacy.ticket import (  # noqa: F401
    Ticket,
    TicketFlag,
    TicketHistory,
    TicketHistoryType,
    TicketIndex,
    TicketLockIndex,
    TicketLockType,
    TicketLoopProtection,
    TicketNumberCounter,
    TicketPriority,
    TicketState,
    TicketStateType,
    TicketType,
    TicketWatcher,
)
from tiqora.db.legacy.types import LegacyDateTime  # noqa: F401
from tiqora.db.legacy.user import (  # noqa: F401
    GroupCustomer,
    GroupCustomerUser,
    GroupRole,
    GroupUser,
    PermissionGroups,
    Roles,
    RoleUser,
    UserPreferences,
    Users,
)

__all__ = [
    "LegacyBase",
    "LegacyDateTime",
    "legacy_metadata",
    "Ticket",
    "TicketHistory",
    "TicketHistoryType",
    "TicketState",
    "TicketStateType",
    "TicketPriority",
    "TicketLockType",
    "TicketType",
    "TicketNumberCounter",
    "TicketWatcher",
    "TicketFlag",
    "TicketIndex",
    "TicketLockIndex",
    "TicketLoopProtection",
    "Article",
    "ArticleFlag",
    "ArticleSenderType",
    "ArticleDataMime",
    "ArticleDataMimePlain",
    "ArticleDataMimeAttachment",
    "ArticleSearchIndex",
    "CommunicationChannel",
    "Queue",
    "QueueAutoResponse",
    "QueueStandardTemplate",
    "StandardTemplate",
    "StandardAttachment",
    "StandardTemplateAttachment",
    "Salutation",
    "Signature",
    "AutoResponse",
    "AutoResponseType",
    "SystemAddress",
    "FollowUpPossible",
    "Sla",
    "Service",
    "ServiceSla",
    "ServiceCustomerUser",
    "Users",
    "UserPreferences",
    "PermissionGroups",
    "Roles",
    "RoleUser",
    "GroupUser",
    "GroupRole",
    "GroupCustomerUser",
    "GroupCustomer",
    "CustomerUser",
    "CustomerCompany",
    "CustomerUserCustomer",
    "CustomerPreferences",
    "DynamicField",
    "DynamicFieldValue",
    "DynamicFieldObjIdName",
    "Acl",
    "Valid",
    "Sessions",
    "MailQueue",
    "PostmasterFilter",
    "GiWebserviceConfig",
    "GenericAgentJobs",
    "SysconfigDefault",
    "SysconfigModified",
    "FormDraft",
    "Mention",
    "TimeAccounting",
    "LinkRelation",
    "LinkType",
    "LinkObject",
    "MailAccount",
]
