#!/usr/bin/env python3
"""Regenerate the bundled S/MIME trust anchors from Mozilla's root store.

Debian's ca-certificates (and certifi) keep only roots trusted for TLS, so
e-mail-only roots such as "HARICA Client RSA Root CA 2021" (GEANT/DFN S/MIME)
are missing there. This takes every root that Mozilla marks as a trusted
delegator for EMAIL_PROTECTION and writes them as one PEM bundle, which
Tiqora adds to S/MIME signature checks (``smime.public_roots``).

Usage:  scripts/update-smime-roots.py [certdata.txt]
Without an argument the current certdata.txt is downloaded from Mozilla.
"""

from __future__ import annotations

import base64
import datetime as dt
import sys
import textwrap
import urllib.request
from pathlib import Path

CERTDATA_URL = (
    "https://hg-edge.mozilla.org/mozilla-central/raw-file/tip/"
    "security/nss/lib/ckfw/builtins/certdata.txt"
)
OUT = Path(__file__).resolve().parent.parent / (
    "backend/src/tiqora/crypto/data/smime-public-roots.crt"
)


def _objects(lines: list[str]) -> list[dict[str, object]]:
    objs: list[dict[str, object]] = []
    cur: dict[str, object] | None = None
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        i += 1
        if not line or line.startswith("#"):
            if not line and cur:
                objs.append(cur)
                cur = None
            continue
        parts = line.split(None, 2)
        if parts[0] == "CKA_CLASS" and cur:
            objs.append(cur)
            cur = None
        if cur is None:
            cur = {}
        if len(parts) >= 2 and parts[1] == "MULTILINE_OCTAL":
            buf = bytearray()
            while lines[i].strip() != "END":
                buf += bytes(int(o, 8) for o in lines[i].strip().split("\\")[1:])
                i += 1
            i += 1
            cur[parts[0]] = bytes(buf)
        elif len(parts) == 3:
            cur[parts[0]] = parts[2]
    if cur:
        objs.append(cur)
    return objs


def _distrusted_now(obj: dict[str, object]) -> bool:
    """CKA_NSS_EMAIL_DISTRUST_AFTER (UTCTime) already in the past."""
    value = obj.get("CKA_NSS_EMAIL_DISTRUST_AFTER")
    if not isinstance(value, bytes):
        return False
    stamp = value.decode("ascii").rstrip("Z")
    when = dt.datetime.strptime(stamp, "%y%m%d%H%M%S").replace(tzinfo=dt.UTC)
    return when < dt.datetime.now(dt.UTC)


def main() -> int:
    if len(sys.argv) > 1:
        text = Path(sys.argv[1]).read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(CERTDATA_URL, timeout=60) as resp:
            text = resp.read().decode("utf-8")
    objs = _objects(text.splitlines())

    trusted: set[tuple[bytes, bytes]] = set()
    for o in objs:
        if (
            o.get("CKA_CLASS") == "CKO_NSS_TRUST"
            and o.get("CKA_TRUST_EMAIL_PROTECTION") == "CKT_NSS_TRUSTED_DELEGATOR"
        ):
            issuer, serial = o.get("CKA_ISSUER"), o.get("CKA_SERIAL_NUMBER")
            if isinstance(issuer, bytes) and isinstance(serial, bytes):
                trusted.add((issuer, serial))

    out: list[str] = []
    for o in objs:
        if o.get("CKA_CLASS") != "CKO_CERTIFICATE":
            continue
        issuer, serial, der = o.get("CKA_ISSUER"), o.get("CKA_SERIAL_NUMBER"), o.get("CKA_VALUE")
        if not (isinstance(issuer, bytes) and isinstance(serial, bytes) and isinstance(der, bytes)):
            continue
        if (issuer, serial) not in trusted or _distrusted_now(o):
            continue
        label = str(o.get("CKA_LABEL", "")).strip('"')
        b64 = "\n".join(textwrap.wrap(base64.b64encode(der).decode("ascii"), 64))
        out.append(f"# {label}\n-----BEGIN CERTIFICATE-----\n{b64}\n-----END CERTIFICATE-----\n")

    header = (
        "# Mozilla root store, roots trusted for e-mail protection (S/MIME).\n"
        "# Generated by scripts/update-smime-roots.py — do not edit by hand.\n"
        f"# {len(out)} roots, {dt.date.today().isoformat()}\n\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + "\n".join(out), encoding="utf-8")
    print(f"wrote {len(out)} roots to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
