/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Queues */
        get: operations["list_queues_api_v1_queues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_v1_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_api_v1_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_v1_tickets__ticket_id__articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/articles/{article_id}/body": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article Body */
        get: operations["get_article_body_api_v1_tickets__ticket_id__articles__article_id__body_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/articles/{article_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attachments */
        get: operations["list_attachments_api_v1_tickets__ticket_id__articles__article_id__attachments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/articles/{article_id}/attachments/by-cid/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attachment By Cid */
        get: operations["get_attachment_by_cid_api_v1_tickets__ticket_id__articles__article_id__attachments_by_cid__content_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/articles/{article_id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attachment */
        get: operations["get_attachment_api_v1_tickets__ticket_id__articles__article_id__attachments__attachment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket History */
        get: operations["ticket_history_api_v1_tickets__ticket_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{login}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_v1_customers__login__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — process is up.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe — critical dependencies reachable.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Prometheus metrics exposition.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArticleBody */
        ArticleBody: {
            /** Article Id */
            article_id: number;
            /** Content Type */
            content_type: string;
            /** Is Html */
            is_html: boolean;
            /** Body */
            body: string;
        };
        /** ArticleListItem */
        ArticleListItem: {
            /** Id */
            id: number;
            /** Ticket Id */
            ticket_id: number;
            /** Sender Type */
            sender_type?: string | null;
            /** Sender Type Id */
            sender_type_id: number;
            /** Communication Channel Id */
            communication_channel_id: number;
            /** Is Visible For Customer */
            is_visible_for_customer: boolean;
            /**
             * Create Time
             * Format: date-time
             */
            create_time: string;
            /** Create By */
            create_by: number;
            /** Subject */
            subject?: string | null;
            /** From Address */
            from_address?: string | null;
            /** To Address */
            to_address?: string | null;
            /** Content Type */
            content_type?: string | null;
            /** Incoming Time */
            incoming_time?: number | null;
        };
        /** AttachmentMetaOut */
        AttachmentMetaOut: {
            /** Id */
            id: number;
            /** Article Id */
            article_id: number;
            /** Filename */
            filename?: string | null;
            /** Content Type */
            content_type?: string | null;
            /** Content Size */
            content_size?: string | null;
            /** Content Id */
            content_id?: string | null;
            /** Disposition */
            disposition?: string | null;
        };
        /** CustomerUserOut */
        CustomerUserOut: {
            /** Login */
            login: string;
            /** Email */
            email: string;
            /** Customer Id */
            customer_id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Title */
            title?: string | null;
            /** Phone */
            phone?: string | null;
            /** Company Name */
            company_name?: string | null;
        };
        /** DynamicFieldValueOut */
        DynamicFieldValueOut: {
            /** Name */
            name: string;
            /** Label */
            label?: string | null;
            /** Field Type */
            field_type?: string | null;
            /** Values */
            values?: unknown[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Id */
            id: number;
            /** Ticket Id */
            ticket_id: number;
            /** Name */
            name: string;
            /** History Type Id */
            history_type_id: number;
            /** History Type */
            history_type?: string | null;
            /** Article Id */
            article_id?: number | null;
            /** Owner Id */
            owner_id: number;
            /**
             * Create Time
             * Format: date-time
             */
            create_time: string;
            /** Create By */
            create_by: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Login */
            login: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserMe"];
        };
        /** PaginatedTickets */
        PaginatedTickets: {
            /** Items */
            items: components["schemas"]["TicketListItem"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** QueueCounts */
        QueueCounts: {
            /**
             * Open
             * @default 0
             */
            open: number;
            /**
             * Locked
             * @default 0
             */
            locked: number;
            /**
             * Unlocked
             * @default 0
             */
            unlocked: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** QueueNode */
        QueueNode: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Group Id */
            group_id: number;
            /** Parent Name */
            parent_name?: string | null;
            /**
             * Valid
             * @default true
             */
            valid: boolean;
            counts?: components["schemas"]["QueueCounts"];
            /** Children */
            children?: components["schemas"]["QueueNode"][];
        };
        /** SearchHit */
        SearchHit: {
            /** Id */
            id: number;
            /** Tn */
            tn?: string | null;
            /** Title */
            title?: string | null;
            /** Queue Id */
            queue_id?: number | null;
            /** Queue Name */
            queue_name?: string | null;
            /** State */
            state?: string | null;
            /** State Type */
            state_type?: string | null;
            /** Priority */
            priority?: string | null;
            /** Owner Login */
            owner_login?: string | null;
            /** Customer Id */
            customer_id?: string | null;
            /** Create Time */
            create_time?: string | null;
            /** Change Time */
            change_time?: string | null;
            /** Excerpt */
            excerpt?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Estimated Total */
            estimated_total: number;
        };
        /** TicketDetail */
        TicketDetail: {
            /** Id */
            id: number;
            /** Tn */
            tn: string;
            /** Title */
            title: string | null;
            /** Queue Id */
            queue_id: number;
            /** Queue Name */
            queue_name?: string | null;
            /** State Id */
            state_id: number;
            /** State */
            state?: string | null;
            /** State Type */
            state_type?: string | null;
            /** Priority Id */
            priority_id: number;
            /** Priority */
            priority?: string | null;
            /** Lock Id */
            lock_id: number;
            /** Lock */
            lock?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Owner Login */
            owner_login?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Customer Id */
            customer_id?: string | null;
            /** Customer User Id */
            customer_user_id?: string | null;
            /**
             * Create Time
             * Format: date-time
             */
            create_time: string;
            /**
             * Change Time
             * Format: date-time
             */
            change_time: string;
            /** Age Seconds */
            age_seconds?: number | null;
            /**
             * Escalation Time
             * @default 0
             */
            escalation_time: number;
            /**
             * Escalation Response Time
             * @default 0
             */
            escalation_response_time: number;
            /**
             * Escalation Update Time
             * @default 0
             */
            escalation_update_time: number;
            /**
             * Escalation Solution Time
             * @default 0
             */
            escalation_solution_time: number;
            /**
             * Until Time
             * @default 0
             */
            until_time: number;
            /** Type Id */
            type_id?: number | null;
            /** Service Id */
            service_id?: number | null;
            /** Sla Id */
            sla_id?: number | null;
            /** Responsible User Id */
            responsible_user_id?: number | null;
            /**
             * Archive Flag
             * @default 0
             */
            archive_flag: number;
            /** Create By */
            create_by?: number | null;
            /** Change By */
            change_by?: number | null;
            /** Dynamic Fields */
            dynamic_fields?: components["schemas"]["DynamicFieldValueOut"][];
        };
        /** TicketListItem */
        TicketListItem: {
            /** Id */
            id: number;
            /** Tn */
            tn: string;
            /** Title */
            title: string | null;
            /** Queue Id */
            queue_id: number;
            /** Queue Name */
            queue_name?: string | null;
            /** State Id */
            state_id: number;
            /** State */
            state?: string | null;
            /** State Type */
            state_type?: string | null;
            /** Priority Id */
            priority_id: number;
            /** Priority */
            priority?: string | null;
            /** Lock Id */
            lock_id: number;
            /** Lock */
            lock?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Owner Login */
            owner_login?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Customer Id */
            customer_id?: string | null;
            /** Customer User Id */
            customer_user_id?: string | null;
            /**
             * Create Time
             * Format: date-time
             */
            create_time: string;
            /**
             * Change Time
             * Format: date-time
             */
            change_time: string;
            /** Age Seconds */
            age_seconds?: number | null;
            /**
             * Escalation Time
             * @default 0
             */
            escalation_time: number;
            /**
             * Escalation Response Time
             * @default 0
             */
            escalation_response_time: number;
            /**
             * Escalation Update Time
             * @default 0
             */
            escalation_update_time: number;
            /**
             * Escalation Solution Time
             * @default 0
             */
            escalation_solution_time: number;
            /**
             * Until Time
             * @default 0
             */
            until_time: number;
        };
        /** UserMe */
        UserMe: {
            /** Id */
            id: number;
            /** Login */
            login: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Auth Method */
            auth_method: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_queues_api_v1_queues_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_v1_tickets_get: {
        parameters: {
            query?: {
                queue_id?: number | null;
                state_id?: number | null;
                state_type?: string | null;
                owner_id?: number | null;
                offset?: number;
                limit?: number;
                sort?: string;
                order?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTickets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_api_v1_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: number;
            };
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_api_v1_tickets__ticket_id__articles_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: number;
            };
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_body_api_v1_tickets__ticket_id__articles__article_id__body_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: number;
                article_id: number;
            };
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attachments_api_v1_tickets__ticket_id__articles__article_id__attachments_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: number;
                article_id: number;
            };
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentMetaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attachment_by_cid_api_v1_tickets__ticket_id__articles__article_id__attachments_by_cid__content_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: number;
                article_id: number;
                content_id: string;
            };
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attachment_api_v1_tickets__ticket_id__articles__article_id__attachments__attachment_id__get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: number;
                article_id: number;
                attachment_id: number;
            };
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticket_history_api_v1_tickets__ticket_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: number;
            };
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_v1_customers__login__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                login: string;
            };
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                offset?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tiqora_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
